/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learning.java;

public class App {
    public String getGreeting() {
        return "Console logging Java way";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
